/**
 * Embed dist/ui assets into a TypeScript module for bundling into the SEA binary.
 * Run after buildUi, before buildNode.
 * Usage: pnpm exec tsx scripts/embed-ui.ts
 */

import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const root = join(__dirname, "..");
const uiDir = join(root, "dist", "ui");
const outFile = join(root, "src", "hub", "embedded-ui.generated.ts");

function collectFiles(dir: string, base = ""): string[] {
  const entries = readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const e of entries) {
    const path = base ? `${base}/${e.name}` : e.name;
    if (e.isDirectory()) {
      files.push(...collectFiles(join(dir, e.name), path));
    } else {
      files.push(path);
    }
  }
  return files;
}

const STUB = `/**
 * Auto-generated by scripts/embed-ui.ts. Do not edit.
 * Stub: run 'pnpm run build' to populate with UI assets.
 */

export const EMBEDDED_UI: Record<string, string> = {};
`;

function main() {
  const outDir = join(root, "src", "hub");
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  if (!existsSync(uiDir)) {
    writeFileSync(outFile, STUB, "utf8");
    console.log("dist/ui not found; wrote stub. Run full build to embed UI.");
    return;
  }

  const files = collectFiles(uiDir);
  const entries: string[] = [];

  for (const rel of files) {
    const abs = join(uiDir, rel);
    const content = readFileSync(abs, "utf8");
    const key = rel.replace(/\\/g, "/");
    entries.push(`  ${JSON.stringify(key)}: ${JSON.stringify(content)},`);
  }

  const ts = `/**
 * Auto-generated by scripts/embed-ui.ts. Do not edit.
 * Contains the Hub UI assets for the single executable build.
 */

export const EMBEDDED_UI: Record<string, string> = {
${entries.join("\n")}
};
`;

  writeFileSync(outFile, ts, "utf8");
  console.log(`Embedded ${files.length} UI files into ${outFile}`);
}

main();
